### PR TITLE
Fix status updates only adding one device per claim

### LINKED ISSUE #117: Device Network data in Status is not updated correctly
It seems only one device gets updated

```
kubectl get resourceclaims -o yaml
apiVersion: v1
items:
- apiVersion: resource.k8s.io/v1beta1
  kind: ResourceClaim
  metadata:
    annotations:
      resource.kubernetes.io/pod-claim-name: rdma-net-interface
    creationTimestamp: "2025-06-17T22:59:48Z"
    finalizers:
    - resource.kubernetes.io/delete-protection
    generateName: nccl-gib-test-0-rdma-net-interface-
    name: nccl-gib-test-0-rdma-net-interface-8dj8b
    namespace: default
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Pod
      name: nccl-gib-test-0
      uid: 0c344e45-9866-4c3f-bc3f-44e8b664bbbd
    resourceVersion: "1750201254435023024"
    uid: 18317a3d-300d-41e3-ba99-4fe78f425d21
  spec:
    devices:
      requests:
      - allocationMode: ExactCount
        count: 8
        deviceClassName: dranet
        name: rdma-net-interface
        selectors:
        - cel:
            expression: device.attributes["dra.net"].rdma == true
  status:
    allocation:
      devices:
        results:
        - adminAccess: null
          device: gpu0rdma0
          driver: dra.net
          pool: gke-dranet-maspinwal-dranet-maspinwal-d3003787-lp53
          request: rdma-net-interface
        - adminAccess: null
          device: gpu1rdma0
          driver: dra.net
          pool: gke-dranet-maspinwal-dranet-maspinwal-d3003787-lp53
          request: rdma-net-interface
        - adminAccess: null
          device: gpu2rdma0
          driver: dra.net
          pool: gke-dranet-maspinwal-dranet-maspinwal-d3003787-lp53
          request: rdma-net-interface
        - adminAccess: null
          device: gpu3rdma0
          driver: dra.net
          pool: gke-dranet-maspinwal-dranet-maspinwal-d3003787-lp53
          request: rdma-net-interface
        - adminAccess: null
          device: gpu4rdma0
          driver: dra.net
          pool: gke-dranet-maspinwal-dranet-maspinwal-d3003787-lp53
          request: rdma-net-interface
        - adminAccess: null
          device: gpu5rdma0
          driver: dra.net
          pool: gke-dranet-maspinwal-dranet-maspinwal-d3003787-lp53
          request: rdma-net-interface
        - adminAccess: null
          device: gpu6rdma0
          driver: dra.net
          pool: gke-dranet-maspinwal-dranet-maspinwal-d3003787-lp53
          request: rdma-net-interface
        - adminAccess: null
          device: gpu7rdma0
          driver: dra.net
          pool: gke-dranet-maspinwal-dranet-maspinwal-d3003787-lp53
          request: rdma-net-interface
      nodeSelector:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - gke-dranet-maspinwal-dranet-maspinwal-d3003787-lp53
    devices:
    - conditions:
      - lastTransitionTime: "2025-06-17T23:00:54Z"
        message: ""
        reason: NetworkDeviceReady
        status: "True"
        type: Ready
      - lastTransitionTime: "2025-06-17T23:00:54Z"
        message: ""
        reason: NetworkReady
        status: "True"
        type: NetworkReady
      device: gpu7rdma0
      driver: dra.net
      networkData:
        hardwareAddress: 62:55:7a:a9:36:16
        interfaceName: gpu7rdma0
        ips:
        - 192.168.8.4/32
      pool: gke-dranet-maspinwal-dranet-maspinwal-d3003787-lp53
    reservedFor:
    - name: nccl-gib-test-0
      resource: pods
      uid: 0c344e45-9866-4c3f-bc3f-44e8b664bbbd
- apiVersion: resource.k8s.io/v1beta1
  kind: ResourceClaim
  metadata:
    annotations:
      resource.kubernetes.io/pod-claim-name: rdma-net-interface
    creationTimestamp: "2025-06-17T23:00:55Z"
    finalizers:
    - resource.kubernetes.io/delete-protection
    generateName: nccl-gib-test-1-rdma-net-interface-
    name: nccl-gib-test-1-rdma-net-interface-j5gzp
    namespace: default
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Pod
      name: nccl-gib-test-1
      uid: 09bdeedc-9981-4b04-9dc6-0fb687b07a2f
    resourceVersion: "1750201286238063000"
    uid: 5eb63421-14fe-4ec8-8903-c74fb2c00143
  spec:
    devices:
      requests:
      - allocationMode: ExactCount
        count: 8
        deviceClassName: dranet
        name: rdma-net-interface
        selectors:
        - cel:
            expression: device.attributes["dra.net"].rdma == true
  status:
    allocation:
      devices:
        results:
        - adminAccess: null
          device: gpu0rdma0
          driver: dra.net
          pool: gke-dranet-maspinwal-dranet-maspinwal-d3003787-zwtv
          request: rdma-net-interface
        - adminAccess: null
          device: gpu1rdma0
          driver: dra.net
          pool: gke-dranet-maspinwal-dranet-maspinwal-d3003787-zwtv
          request: rdma-net-interface
        - adminAccess: null
          device: gpu2rdma0
          driver: dra.net
          pool: gke-dranet-maspinwal-dranet-maspinwal-d3003787-zwtv
          request: rdma-net-interface
        - adminAccess: null
          device: gpu3rdma0
          driver: dra.net
          pool: gke-dranet-maspinwal-dranet-maspinwal-d3003787-zwtv
          request: rdma-net-interface
        - adminAccess: null
          device: gpu4rdma0
          driver: dra.net
          pool: gke-dranet-maspinwal-dranet-maspinwal-d3003787-zwtv
          request: rdma-net-interface
        - adminAccess: null
          device: gpu5rdma0
          driver: dra.net
          pool: gke-dranet-maspinwal-dranet-maspinwal-d3003787-zwtv
          request: rdma-net-interface
        - adminAccess: null
          device: gpu6rdma0
          driver: dra.net
          pool: gke-dranet-maspinwal-dranet-maspinwal-d3003787-zwtv
          request: rdma-net-interface
        - adminAccess: null
          device: gpu7rdma0
          driver: dra.net
          pool: gke-dranet-maspinwal-dranet-maspinwal-d3003787-zwtv
          request: rdma-net-interface
      nodeSelector:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - gke-dranet-maspinwal-dranet-maspinwal-d3003787-zwtv
    devices:
    - conditions:
      - lastTransitionTime: "2025-06-17T23:01:26Z"
        message: ""
        reason: NetworkDeviceReady
        status: "True"
        type: Ready
      - lastTransitionTime: "2025-06-17T23:01:26Z"
        message: ""
        reason: NetworkReady
        status: "True"
        type: NetworkReady
      device: gpu6rdma0
      driver: dra.net
      networkData:
        hardwareAddress: 92:77:04:06:a2:13
        interfaceName: gpu6rdma0
        ips:
        - 192.168.7.5/32
      pool: gke-dranet-maspinwal-dranet-maspinwal-d3003787-zwtv
    reservedFor:
    - name: nccl-gib-test-1
      resource: pods
      uid: 09bdeedc-9981-4b04-9dc6-0fb687b07a2f
- apiVersion: resource.k8s.io/v1beta1
  kind: ResourceClaim
  metadata:
    annotations:
      resource.kubernetes.io/pod-claim-name: rdma-net-interface
    creationTimestamp: "2025-06-17T23:15:16Z"
    generateName: nccl-gib-test-4w-0-rdma-net-interface-
    name: nccl-gib-test-4w-0-rdma-net-interface-7f9gq
    namespace: default
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Pod
      name: nccl-gib-test-4w-0
      uid: e93f4e36-ae83-4701-85f6-dfeb25bdfe38
    resourceVersion: "1750202116244175024"
    uid: c7b82de3-bb74-484d-b769-eb3d1a3edcb2
  spec:
    devices:
      requests:
      - allocationMode: ExactCount
        count: 4
        deviceClassName: dranet
        name: rdma-net-interface
        selectors:
        - cel:
            expression: |
              device.attributes["dra.net"].rdma == true &&
              (
                (device.attributes["dra.net"].ifName.startsWith("gpu") &&
                 device.attributes["dra.net"].ifName.endsWith("rdma0") &&
                 int(device.attributes["dra.net"].ifName.substring(3, 4)) < 4)
              ||
                (device.attributes["dra.net"].ifName.startsWith("gpu") &&
                 device.attributes["dra.net"].ifName.endsWith("rdma0") &&
                 int(device.attributes["dra.net"].ifName.substring(3, 4)) >= 4)
              )
  status: {}
kind: List
metadata:

```

### PR DESCRIPTION
**Pull request by michaelasp**
Due to SSA tracking owners, we need to do a batch update of status at the end of our NRI loop. Fix this by tracking all status updates needed and doing a batch update at the end.

Fixes #117

### CODE REVIEW

**Comment by michaelasp** [comment]
> How hard is adding a bats e2e test to avoid regression?

Shouldn't be too difficult. Let me try it out!

**Review by gauravkghildiyal — COMMENTED** [review]
Thank you!

Just a few nits

File: pkg/driver/nri_hooks.go [hunk 1]
```diff
@@ -179,22 +188,25 @@ func (np *NetworkDriver) RunPodSandbox(ctx context.Context, pod *api.PodSandbox)
...
+			_, err := np.kubeClient.ResourceV1beta1().ResourceClaims(claim.Namespace).ApplyStatus(ctxStatus,
 				resourceClaimApply,
 				metav1.ApplyOptions{FieldManager: np.driverName, Force: true},
 			)
 			if err != nil {
-				klog.Infof("failed to update status for claim %s/%s : %v", config.Claim.Namespace, config.Claim.Name, err)
+				klog.Infof("failed to update status for claim %s/%s : %v", claim.Namespace, claim.Name, err)
 			} else {
-				klog.V(4).Infof("update status for claim %s/%s", config.Claim.Namespace, config.Claim.Name)
+				klog.V(4).Infof("update status for claim %s/%s", claim.Namespace, claim.Name)
```
[the remark this answers is not in the document]
Comment (michaelasp) [reply pkg/driver/nri_hooks.go]: Done!

File: tests/e2e.bats [hunk 2]
```diff
@@ -175,3 +175,32 @@
...
+  docker exec "$CLUSTER_NAME"-worker bash -c "ip link add dummy7 type dummy"
+  docker exec "$CLUSTER_NAME"-worker bash -c "ip link set up dev dummy7"
+  docker exec "$CLUSTER_NAME"-worker bash -c "ip addr add 169.254.169.14/32 dev dummy7"
+
+  kubectl apply -f "$BATS_TEST_DIRNAME"/../examples/deviceclass.yaml
+  kubectl apply -f "$BATS_TEST_DIRNAME"/../examples/resourceclaimtemplate_double.yaml
+  kubectl wait --timeout=30s --for=condition=ready pods -l app=MyApp
+  POD_NAME=$(kubectl get pods -l app=MyApp -o name)
+  run kubectl exec $POD_NAME -- ip addr show dummy6
+  [ "$status" -eq 0 ]
```
Comment (gauravkghildiyal) [inline tests/e2e.bats:194]: If you rebase, you'll find a different pattern being used to perform assertions in bats tests. Please use those instead since they log both the got/want ouptuts.

Comment (michaelasp) [reply tests/e2e.bats:194]: Gotcha! Looks like this is failing at the moment anyways so I need to go back.

Comment (michaelasp) [reply tests/e2e.bats:245]: Done!
