### PR TITLE
fix: Delete singleton links if they are removed

### LINKED ISSUE #155: Deleting Devices can Lead to Stalled Pods
While working on creating a cleanup function to make e2e tests atomic I ran into a bug with device deletion.

Deleting a device fails other tests with a interesting error message using the device name of a previous test

```
Warning  FailedPrepareDynamicResources  16s (x3 over 2m50s)  kubelet            Failed to prepare dynamic resources: NodePrepareResources failed for claim default/dummy-interface-static-ip-route: claim c21de403-2648-4e2d-837b-68ca1a64ff6c contain errors: fail to get network interface mlx5_6
```

When there is a newly available interface available for allocation named dummy0. Not sure if this is an issue with DRA or DraNet. The issue seems to be around not removing a device if it was deleted and assigned to a pod. We might have some dangling references to deleted interfaces that we need to reconcile.

### PR DESCRIPTION
**Pull request by michaelasp**
Currently if a link is deleted as the last link the driver will never reconcile and leave it in the resource slice. Ensure that this does not happen since that could lead to bad assignments by the scheduler. Can easily replicate the issue by creating a cluster and adding then removing a link.

Fixes #155

### CODE REVIEW

File: pkg/inventory/db.go [hunk 1]
```diff
@@ -176,7 +177,8 @@ func (db *DB) Run(ctx context.Context) error {
 		}
 
 		klog.V(4).Infof("Found %d devices", len(devices))
-		if len(devices) > 0 {
+		if len(devices) > 0 || db.hasDevices {
+			db.hasDevices = len(devices) > 0
```
Comment (michaelasp) [inline pkg/inventory/db.go:181]: This might be racy. Please check.

Comment (aojea) [reply pkg/inventory/db.go:181]: I do not see a concurrent access to the boolean
